-- MySQL Script generated by MySQL Workbench
-- 12/07/15 23:30:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dokumentasi_LFS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dokumentasi_LFS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dokumentasi_LFS` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dokumentasi_LFS` ;

-- -----------------------------------------------------
-- Table `dokumentasi_LFS`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dokumentasi_LFS`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NULL,
  `kelas` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dokumentasi_LFS`.`Dokumentasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dokumentasi_LFS`.`Dokumentasi` (
  `idDokumentasi` INT NOT NULL,
  `waktu` DATETIME NULL,
  `judul` VARCHAR(255) NULL,
  `keterangan` VARCHAR(500) NULL,
  `user_iduser` INT NOT NULL,
  `nrp` VARCHAR(45) NULL,
  PRIMARY KEY (`idDokumentasi`, `user_iduser`),
  INDEX `fk_Dokumentasi_user_idx` (`user_iduser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dokumentasi_LFS`.`mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dokumentasi_LFS`.`mahasiswa` (
  `nrp` VARCHAR(20) NOT NULL,
  `nama` VARCHAR(45) NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`nrp`, `user_iduser`),
  INDEX `fk_mahasiswa_user1_idx` (`user_iduser` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
